###############
## 
####

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Debanding'
  SESSION: 'UNet'
  VARIANT: 'UNet-32'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 400
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-5
  LR_MIN: 1e-7
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: True
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './datasets/VP9BandingDataset/train' # path to training data
  VAL_DIR: './datasets/VP9BandingDataset/val'    # path to validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  SAVE_IMAGES: True
